# Generated by Django 4.2.30 on 2026-06-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "swapi_url",
                    models.URLField(
                        db_index=True,
                        help_text="Canonical SWAPI resource URL; used as the natural key for upserts.",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("episode_id", models.PositiveSmallIntegerField()),
                ("director", models.CharField(blank=True, max_length=255)),
                ("producer", models.CharField(blank=True, max_length=255)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("opening_crawl", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["episode_id"],
            },
        ),
        migrations.CreateModel(
            name="Starship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("swapi_url", models.URLField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("model", models.CharField(blank=True, max_length=255)),
                ("starship_class", models.CharField(blank=True, max_length=255)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                (
                    "cost_in_credits",
                    models.CharField(
                        blank=True,
                        help_text="Stored as text: SWAPI returns 'unknown' for some values.",
                        max_length=64,
                    ),
                ),
                ("length", models.CharField(blank=True, max_length=64)),
                ("crew", models.CharField(blank=True, max_length=64)),
                ("passengers", models.CharField(blank=True, max_length=64)),
                ("hyperdrive_rating", models.CharField(blank=True, max_length=64)),
                (
                    "films",
                    models.ManyToManyField(blank=True, related_name="starships", to="catalog.film"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("swapi_url", models.URLField(db_index=True, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("birth_year", models.CharField(blank=True, max_length=32)),
                ("gender", models.CharField(blank=True, max_length=32)),
                ("height_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("mass_kg", models.PositiveIntegerField(blank=True, null=True)),
                ("hair_color", models.CharField(blank=True, max_length=64)),
                ("skin_color", models.CharField(blank=True, max_length=64)),
                ("eye_color", models.CharField(blank=True, max_length=64)),
                (
                    "films",
                    models.ManyToManyField(
                        blank=True, related_name="characters", to="catalog.film"
                    ),
                ),
                (
                    "starships",
                    models.ManyToManyField(
                        blank=True, related_name="pilots", to="catalog.starship"
                    ),
                ),
            ],
            options={
                "verbose_name": "Character",
                "verbose_name_plural": "Characters",
                "ordering": ["name"],
            },
        ),
    ]
